= Lab 9 - Working with Docker Compose

In this lab we're going to deploy the same Spring Boot application again, but this time we will persist the data in a MySQL container. We'll use Docker Compose to facilitate spinning up the two containers and linking them as a unit.

You'll find the Docker Compose config at `ContainersWorkshop/code/compose/docker-compose.yml`:

====
[source,yaml]
----
include::../code/compose/docker-compose.yml[]
----
<1> First we specify a container to be named `mysql`.
<2> The `mysql` container will be based on the `mysql` image (latest implied).
<3> The `mysql` image requires that we either explicitly specify (via environment variables) a root password for the database or that we explicitly specify that the root password should be blank. We choose the former.
<4> The `mysql` image will create a default DB on startup, with a default user and password. The next 3 environment variables accomplish that.
<5> Next we specify a container to be named `web`.
<6> The `web` container will be based on the `docker-spring-boot` image we created in the earlier labs.
<7> We expose port 8080 to allow us to talk to our application.
<8> We create a link to the `mysql` container for data persistence.
<9> We set 3 environment variables. `SPRING_PROFILES_ACTIVE: docker` turns on a profile that tells our app to look for Docker link variables for the IP and Port for MySQL. The other 2 variables specify the username and password.
====

You can look at `ContainersWorkshop/code/docker-spring-data-rest/src/main/resources/application.yml` to see how the `docker` profile configures the Spring app:

====
[source,yaml]
----
include::../code/docker-spring-data-rest/src/main/resources/application.yml[tag=spring_profile_docker]
----
<1> We're using Spring Boot's ability to interpolate environment variables to pull in the Docker link IP and Port.
<2> We're doing the same to pull in the environment variables we set manually to get the username and password.
====

. Boot just the MySQL container using Docker Compose:
+
----
$ cd ContainersWorkshop/code/compose
$ docker-compose up mysql
Creating compose_mysql_1...
Attaching to compose_mysql_1
mysql_1 | Running mysql_install_db

...

mysql_1 | 2015-07-21 22:26:58 1 [Note] Event Scheduler: Loaded 0 events
mysql_1 | 2015-07-21 22:26:58 1 [Note] mysqld: ready for connections.
mysql_1 | Version: '5.6.25'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
----
+
The MySQL DB image goes through an initialization process that starts and stops the server a few times. If we tried to start the Spring Boot app at the same time, the connection would fail when the app tries to start.

. Use `CTRL-C` to stop the MySQL image.

. Use Docker Compose to start both the DB and app:
+
----
$ docker-compose up

...

web_1   | 2015-07-21 22:29:00.534  INFO 1 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
web_1   | 2015-07-21 22:29:00.732  INFO 1 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
web_1   | 2015-07-21 22:29:00.734  INFO 1 --- [           main] c.d.d.DockerSpringDataRestApplication    : Started DockerSpringDataRestApplication in 10.287 seconds (JVM running for 11.123)
----

. Access the application using your boot2docker IP using cURL or in a browser:
+
----
$ curl -i http://192.168.59.103:8080/languages
HTTP/1.1 200 OKServer: Apache-Coyote/1.1
X-Application-Context: application
Content-Type: application/hal+json;charset=UTF-8
Transfer-Encoding: chunkedDate: Tue, 21 Jul 2015 13:31:11 GMT

{
  "_links" : {
    "self" : {
      "href" : "http://192.168.59.103:8080/languages{?page,size,sort}",
      "templated" : true
    }
  },
  "_embedded" : {
    "languages" : [ {
      "name" : "Java",
      "creator" : "Gosling",
      "_links" : {
          "self" : {
          "href" : "http://192.168.59.103:8080/languages/1"
        }
      }
    }, {
      "name" : "Perl",
      "creator" : "Wall",
      "_links" : {
        "self" : {
          "href" : "http://192.168.59.103:8080/languages/2"
        }
      }
      ...
----

. Run a MySQL client container to show that the data is in fact in MySQL:
+
----
$ docker run -it --link compose_mysql_1:mysql --rm mysql sh -c 'exec mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -uroot -p"$MYSQL_ENV_MYSQL_ROOT_PASSWORD"'
Warning: Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 11
Server version: 5.6.25 MySQL Community Server (GPL)

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use languages;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from languages;
+----+---------+---------+
| id | creator | name    |
+----+---------+---------+
|  1 | Gosling | Java    |
|  2 | Wall    | Perl    |
|  3 | Matz    | Ruby    |
|  4 | Rich    | Clojure |
+----+---------+---------+
4 rows in set (0.00 sec)
----

. Shutdown the apps using `CTRL-C`.
+
----
^CGracefully stopping... (press Ctrl+C again to force)
Stopping compose_web_1...
Stopping compose_mysql_1...

Aborting.
----
