:compat-mode:
= Lab 2 - Getting to Know the Docker CLI

In this lab we'll get to know some basic Docker CLI commands. Many of these will come in handy as part of your regular Docker workflow.

== `docker info`

This command provides you with the details of your current Docker environment. Most of the information here describes your boot2docker VM:

----
$ docker info
Containers: 6
Images: 110
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 122
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.7-boot2docker
Operating System: Boot2Docker 1.7.1 (TCL 6.3); master : c202798 - Wed Jul 15 00:16:02 UTC 2015
CPUs: 8
Total Memory: 1.955 GiB
Name: boot2docker
ID: 55C2:KW6J:7B7Z:7ZAP:NYCM:6O6C:F6MW:SBYA:RCB5:QOQ6:UD4Q:XVV7
Debug mode (server): true
File Descriptors: 24
Goroutines: 42
System Time: 2015-07-21T04:39:20.271351235Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: mstine
Registry: https://index.docker.io/v1/
----

== More commands:

For the next several commands, you'll want to first run a Docker container:

----
$ docker run -d busybox sh -c 'while true; do echo yo && sleep 5; done'
----

This command does exactly what you think to does: echo ``yo'' to `STDOUT` in an infinite loop. You won't see this output because `-d` runs this container in detached or background mode.

=== `docker ps`

Much like we can use the `ps` command on *nix systems to learn about what processes are running, we can use `docker ps` to learn about what containers are running:

----
$ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED              STATUS              PORTS               NAMES4f292e2e7c86        busybox             "sh -c 'while true;    About a minute ago   Up About a minute                       elated_bartik
----

Importantly, this command tells us:

* the container's ID
* from what image it was created
* the command that was started
* any mapped ports (we'll get to this later!)
* the name of the container

=== `docker inspect`

To learn all of the low-level details of our container's metadata, we can use `docker inspect`:

----
$ docker inspect 4f292e2e7c86
[{
    "Id": "4f292e2e7c86d5f6905476cd27177c1af8337e4f792c5d0c74b84e9197dbca83",
    "Created": "2015-07-21T05:02:16.710625682Z",
    "Path": "sh",
    "Args": [
        "-c",
        "while true; do echo yo \u0026\u0026 sleep 5; done"
    ],
    "State": {
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 954,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-07-21T05:02:17.138080575Z",
        "FinishedAt": "0001-01-01T00:00:00Z"    },
    "Image": "8c2e06607696bd4afb3d03b687e361cc43cf8ec1a4a725bc96e39f05ba97dd55",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "5cee11a9940bbd7f695f79f19e3ea3d8d1452b071a8e8e9b4dd4507ef30b17bf",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.1",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:01",
        "NetworkID": "b234cae4627ec09423532e6868715d27650b2feea4b83b6f8701116b1ecf323e",
        "PortMapping": null,
        "Ports": {},
        "SandboxKey": "/var/run/docker/netns/4f292e2e7c86",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
        },
    "ResolvConfPath": "/mnt/sda1/var/lib/docker/containers/4f292e2e7c86d5f6905476cd27177c1af8337e4f792c5d0c74b84e9197dbca83/resolv.conf",
    "HostnamePath": "/mnt/sda1/var/lib/docker/containers/4f292e2e7c86d5f6905476cd27177c1af8337e4f792c5d0c74b84e9197dbca83/hostname",
    "HostsPath": "/mnt/sda1/var/lib/docker/containers/4f292e2e7c86d5f6905476cd27177c1af8337e4f792c5d0c74b84e9197dbca83/hosts",
    "LogPath": "/mnt/sda1/var/lib/docker/containers/4f292e2e7c86d5f6905476cd27177c1af8337e4f792c5d0c74b84e9197dbca83/4f292e2e7c86d5f6905476cd27177c1af8337e4f
792c5d0c74b84e9197dbca83-json.log",
    "Name": "/elated_bartik",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "Volumes": {},
    "VolumesRW": {},
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "Privileged": false,
        "PortBindings": {},
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "bridge",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "RestartPolicy": {
            "Name": "no",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": ""
    },
    "Config": {
        "Hostname": "4f292e2e7c86",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "PortSpecs": null,
        "ExposedPorts": null,
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": null,
        "Cmd": [
            "sh",
            "-c",
            "while true; do echo yo \u0026\u0026 sleep 5; done"
        ],
        "Image": "busybox",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {}
    }
}
]
----

=== `docker logs`

Want to see what your container is doing? More specifically, what it is writing to `STDOUT` and/or `STDERR`? Use `docker logs`.

In this example, we'll tail the last ten lines:

----
$ docker logs --tail=10 elated_bartik
yo
yo
yo
yo
yo
yo
yo
yo
yo
yo
----

=== `docker kill`

Sending a `SIGKILL` to a container is as simple as `docker kill`:

----
$ docker kill 4f292e2e7c86
4f292e2e7c86
----

=== `docker start`

If you immediately run a `docker ps -a` after this (`-a` is the ``all'' flag):

----
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS                        PORTS               NAMES
4f292e2e7c86        busybox             "sh -c 'while true;    9 minutes ago       Exited (137) 55 seconds ago                       elated_bartik
----

You'll notice that the container is still hanging around. In fact, we could restart it with `docker start elated_bartik`.

=== `docker rm`

Maybe we don't want to restart the container. In fact, we want to clean up the stale union filesystem. We can accomplish that with `docker rm`:

----
$ docker rm 4f292e2e7c86
4f292e2e7c86
----

Which leaves behind a very lonely `docker ps`:

----
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
----

A useful alias you might create that will clean up all stale containers:

----
alias dcc='docker rm -v $(docker ps -f "status=exited" -q)'
----

This command searches for all containers that have `exited` and outputs only their ID's (`-q`). Each ID is passed to `docker rm -v`. The `-v` argument will clean up any persistent volumes (this can be very important, as dangling volumes are harder to get rid off with the current Docker tooling). We'll cover volumes later.
